### ISSUE TITLE
Old Facebook call keeps opening a DM room

### ISSUE THREAD

**Issue by vranki** [mautrix/facebook#113]
Steps to reproduce:

1. Setup bridge and login
2. Have someone make a facebook call to you (don't answer)
3. Bridge opens a new DM room with no messages from the caller
4. Wonder what's happening, close the DM room.
5. After a while goto 3

I haven't figured out a way to prevent this.

**Comment by hwittenborn** [comment]
I think the bridge just syncs all open chats(which would include chats only mentioning missed calls), so I imagine you can just close the DM on Messenger to stop the room creation on Synapse.

**Comment by vranki** [comment]
Nope, closing it on Matrix and FB side has no effect.

**Comment by hwittenborn** [comment]
I'm assuming you've already done it, but if you haven't, maybe try running `refresh`?

Though I think it already does that, which results in it adding rooms if deleted from Synapse(don't quote me on that though).

Outside of that, I'm pretty clueless - no clue if it's even related, but maybe try messing around with [this setting](https://github.com/tulir/mautrix-facebook/blob/master/mautrix_facebook/example-config.yaml#L116-L119).

**Comment by vranki** [comment]
This stopped happening for me. No clue if it's fixed now or is it just random. Maybe someone could try to reproduce this with actual facebook account to verify if it's fixed?

**Comment by ToeiRei** [comment]
I do have the same problem. Every restart I get a ton of 'DMs' which I already left - as if the bridge doesn't keep track of if the messages are fresh or not.

**Comment by sumnerevans** [comment]
Did you leave the DM from Facebook or just from Matrix?

**Comment by ToeiRei** [comment]
I wasn't even aware that facebook had the option to 'leave' a DM. All I could do was marking all as read

**Comment by ToeiRei** [comment]
looks like I have to archive the old chats to prevent them from flooding in.
