### ISSUE TITLE
User account based relay bridge

### ISSUE THREAD

**Issue by homebeach** [mautrix/facebook#13]
Use Facebook user account as a relay bridge as Facebook does not support bots.

**Comment by homebeach** [comment]
How about adding "relay mode"? When this is set on, your Facebook user will relay messages of Matrix users into Facebook group chat.

**Comment by mrjohnson22** [comment]
For now, [matrix-imposter-bot](https://github.com/mrjohnson22/matrix-imposter-bot) can be used to effectively add a relay mode to this bridge.

**Comment by homebeach** [comment]
Why not to just merge the functionality with the main project?

**Comment by itsmeboy0** [comment]
Added in https://github.com/mautrix/facebook/commit/b8188fa051ccc8349830397f32ce2e1867186f35 I assume?

**Comment by HansJK** [comment]
So now you can be multiple matrix accounts in a room bridged to FB Messenger
With the name of the senders name showing up like this?
![Screenshot 2021-12-14 at 18 03 57](https://user-images.githubusercontent.com/37002225/146045220-e1df1237-5c27-4fa2-a7a5-8290618e9a5c.png)
![Screenshot 2021-12-14 at 18 04 14](https://user-images.githubusercontent.com/37002225/146045268-1295b8df-2adc-4059-b327-a3d4581ed915.png)
?

**Comment by JuniorJPDJ** [comment]
yes
