### ISSUE TITLE
Delay sending disconnected warnings and suppress if connection is restored in short time

### ISSUE THREAD

**Issue by MurzNN** [mautrix/facebook#157]
Almost every day I receive the message `Disconnected from Facebook Messenger: MQTT Error: no connection, retrying in 0 seconds`, and immediately after this - `Connected to Facebook Messenger`, that looks too noisy.

Will be good to add the option for delay sending disconnected warnings and suppress them, if connection is restored in given period.

**Comment by CarlAmbroselli** [comment]
@MurzNN this is now supported using the config option `temporary_disconnect_notices` in the bridge config:
https://github.com/mautrix/facebook/blob/6cdcbc21e2489159887c6d529cac80f6cd05b4c1/mautrix_facebook/example-config.yaml#L225
