### ISSUE TITLE
Shared Posts Show as "Unsupported shared media attachment"

### ISSUE THREAD

**Issue by mibzman** [mautrix/facebook#170]
if I:
1. see a post in my feed
2. hit 'share'
3. share to messages
4. send it to myself

it comes out of the bridge reading:
```
<p>Unsupported shared media attachment</p>
<blockquote>the first 200 characters of the post text</blockquote>
```

The source shows an `external_url`, which links to the post.  Can that external_url link be in the message?

I believe the relevant code is [here](https://github.com/tulir/mautrix-facebook/blob/6d47be647d7f097a8ddb7e40df42010c70757e44/mautrix_facebook/portal.py#L902)

**Comment by JuniorJPDJ** [comment]
If you found needed code, try doing pull request with your idea.
