### ISSUE TITLE
Incorrect behaviour when editing a message

### ISSUE THREAD

**Issue by natoleet** [mautrix/facebook#211]
When editing a previously sent message it appears as "edited" in the matrix client. However instead of appearing "edited" for other Facebook Messenger users it sends the entire message again.

The expected behaviour is to edit the message as if it were edited using Facebook Messenger.

**Comment by jtagcat** [comment]
Messenger has 'unsending' messages. Could editing a message cause an unsend + resend with edited contents? It'd be nice if it'd keep the same reply as original, and if original was not a reply, reply to either the deleted, or previous (same author?) message of deleted (or neither).
