### ISSUE TITLE
Bridge triggered blocking, logged-in checkpoint

### ISSUE THREAD

**Issue by CarlAmbroselli** [mautrix/facebook#226]
Got the following error this morning from the Facebook bridge bot:

```
Got authentication error from Messenger:

> 190.490: The user is enrolled in a blocking, logged-in checkpoint

If you changed your Facebook password or enabled two-factor authentication, this is normal and you just need to log in again.
```

This is what I get when I log into Facebook:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/783831/158540610-25e4a688-f667-48cb-a308-b40ee2a81de8.png">

After going through the unlock process and changing the password I'm able to use the bridge again.

**Comment by tulir** [comment]
It happens sometimes, it's mentioned in the [docs](https://docs.mau.fi/bridges/python/facebook/authentication.html)
