### ISSUE TITLE
Having trouble with getting the bridge to read the Postgres database (Dendrite): foreign table

### ISSUE THREAD

**Issue by rowanad** [mautrix/facebook#232]
The database appears to have a a foreign table"goose_db_version" so the bridge terminates on startup. 
The logs for the bridge tell me that I can use a "--ignore-foreign-tables" flag to ignore the error and proceed but I can't work out how I can pass this option to the function that requires it. Can it be done using the config.yaml? 

If not, perhaps option this can be added to the config?

As a workaround, I have tried deleting the table, but it is simply regenerated so the error persists.

**Comment by tulir** [comment]
Don't share databases between different programs.

The flag is just a command-line parameter, as in `python -m mautrix_facebook --ignore-foreign-tables` (although there's currently no easy way to pass it when using docker, some solution for docker will come in the future)
