### ISSUE TITLE
Cannot login to messenger, blocked because IP difference

### ISSUE THREAD

**Issue by AriBerisha** [mautrix/facebook#233]
Hello, hope you are well

Whenever I try to bridge facebook, I get the following error after I input password"
"Your account is temporarily unavailable. Regain access by updating the app or logging in from a mobile or web browser." 
This is due to the IP coming from France, how do I disable such feature in facebook?

Best Regards

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/python/facebook/authentication.html mentions some workarounds at the bottom
