### ISSUE TITLE
Invalid method encountered when trying to open room with the bot

### ISSUE THREAD

**Issue by bzp99** [mautrix/facebook#240]
I have successfully used `mautrix_facebook` before with _Synapse_ but recently tried to switch over to _Dendrite._
I used the same configuration as before for the appservice, but when I try to open a chat with the bot, it does not join.

In `mautrix_facebook`’s logs:
```
[2022-05-06 10:48:21,873] [INFO@aiohttp.access] ::1 [06/May/2022:08:48:21 +0000] "UNKNOWN / HTTP/1.0" 400 204 "-" "-"
[2022-05-06 10:48:21,874] [ERROR@aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/mautrixfb_/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

In the meantime, in _Dendrite’s_ logs:
```
May  6 12:49:14 dendrite_[93478]: time="2022-05-06T10:49:14.517881692Z" level=warning msg="unable to send transactions successfully, backing off for 64s" appservice=facebook error="Put \\"http://localhost:29319/transactions/1?access_token=[redacted]\\": http: server gave HTTP response to HTTPS client"
```

I am not sure if the two entries are related, but the end result is that I cannot interact with the bot.

This is _Dendrite_ **0.8.2+9957752a** and `mautrix_facebook` **0.4.0.**

**Comment by tulir** [comment]
> Put \\"http://localhost:29319/transactions/1?access_token=[redacted]\\": http: server gave HTTP response to HTTPS client

Looks like a misconfigured bridge address in the registration file or a dendrite bug (the log says it's connecting to http, so I'm not sure why it's expecting a tls response).

**Comment by bzp99** [comment]
The URL in the registration file seems  correct:

```
id: facebook
[...]
url: http://localhost:29319
```

There is no TLS involved, so I am puzzled about the error message. I suppose I should report this at Dendrite then…
