### ISSUE TITLE
If you add a FB puppet user to a space as a member, it breaks the PM with them

### ISSUE THREAD

**Issue by kubo6472** [mautrix/facebook#242]
For some reason I noticed that the puppet user in PMs does not react to !fb commands, when in a group of two others it works, then I noticed I added that matrix account as a space member, so I kicked it and recreated the PM, no luck. Facebook bridge bot simply does not think that room is a bridge. Is there a way to manually forcefully bridge a room to a PM?

**Comment by tulir** [comment]
This was fixed already, the bridge will reject space invites now. Deleting the row in the `portal` table is probably the easiest way to fix previously broken rooms

**Comment by kubo6472** [comment]
> This was fixed already, the bridge will reject space invites now. Deleting the row in the `portal` table is probably the easiest way to fix previously broken rooms

Oh aight, how to delete a table please? I deployed this with the ansible script, so it makes me a bit sw unaware, sry for this. Does this also use postgres, or some other kind of DB for "portal table"?
