### ISSUE TITLE
DM invites have weird behaviour (Empty Room, Crashing Element)

### ISSUE THREAD

**Issue by MaximilianGaedig** [mautrix/facebook#252]
DM invites have insufficient information and get displayed as Empty Rooms

## Element soft-crashes

This relates to [this Element Desktop/Web issue](https://github.com/vector-im/element-web/issues/22710), Element soft-crashes when receiving an DM invite from mautrix-facebook: 
![image](https://user-images.githubusercontent.com/38767445/179565483-9623df2f-f3c9-42be-a0d2-5d2517603a73.png)

On Element Android and Gomuks you can accept them, but they still get shown as Empty Rooms until Accepted:
![image](https://user-images.githubusercontent.com/38767445/179565522-3eb84466-2a4d-44fd-8fcc-41be686f4506.png)

mautrix-facebook version: 0.4.0+dev.0ce05887
dendrite version: 0.8.9

**Comment by tulir** [comment]
Doesn't sound like a bridge issue

**Comment by MaximilianGaedig** [comment]
When I was using some version around 0.3 of mautrix-facebook, invites had proper naming, not Empty Room so something with the bridge probably changed.
