### ISSUE TITLE
Can't logout because I am logged in

### ISSUE THREAD

**Issue by NekoSpirits** [mautrix/facebook#259]
![image](https://user-images.githubusercontent.com/20034469/192103543-8a9dc6b9-510b-44ff-9911-d2faff72a15d.png)

Bot thinks that I am logged out, so no chats appear, can't logout and log back in, can't do much of anything at the moment.

**Comment by prurigro** [comment]
I was able to solve this by restarting the mautrix-facebook service, but it didn't fix the reason I first logged out (messages recently stopped getting sent)
