### ISSUE TITLE
⚠ Your message may not have been bridged: Messages sent before updating will not be delivered.

### ISSUE THREAD

**Issue by prurigro** [mautrix/facebook#260]
Messages are still getting received, but as of recently (things were working on Friday, went away for the weekend and now they're not) I started getting this message when trying to send any (and have confirmed they aren't showing up on Facebook).

I tried logging out and back in and ran into this issue https://github.com/mautrix/facebook/issues/259 (not sure if that's related) -- but after restarting the service I was marked as logged in again. After that I continued to have the same problem sending messages.

Here's what I see in the log:

```
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]: [2022-09-26 16:41:23,363] [DEBUG@mau.portal.xxxxxxxxxxxxxxx<->xxxxxxxxxxxxxxx] Error handling Matrix message $BYmfUMcfeUjVfXT0klkhVl6oDdF747l5L0iLmUg3qkQ: Messages sent before updating will not be delivered.
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]: [2022-09-26 16:41:23,363] [ERROR@mau.portal.xxxxxxxxxxxxxxx<->xxxxxxxx] Failed to handle Matrix event $BYmfUMcfeUjVfXT0klkhVl6oDdF747l5L0iLmUg3qkQ: Messages sent before updating will not be delivered.
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]: Traceback (most recent call last):
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:   File "/var/lib/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 752, in handle_matrix_message
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:     await self._handle_matrix_message(sender, message, event_id)
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:   File "/var/lib/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 780, in _handle_matrix_message
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:     await self._handle_matrix_text(event_id, sender, message)
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:   File "/var/lib/mautrix-facebook/lib/python3.10/site-packages/mautrix_facebook/portal.py", line 820, in _handle_matrix_text
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]:     raise Exception(resp.error_message)
Sep 26 16:41:23 tornode.darkcloud.ca python[360985]: Exception: Messages sent before updating will not be delivered.
```

**Comment by prurigro** [comment]
A small update- the issue remains consistent. Messages are received correctly, checking messages on facebook removes the unread marker in element, and the other person checking messages updates their "read to" marker in element. Sending messages continues to create an error with the three lines in the log.

752 is a try for `self._handle_matrix_message`
780 is a `self._handle_matrix_text` in the `_handle_matrix_message` function
820 is a `raise Exception` in `_handle_matrix_text`

So while it pinpoints where the issue is, it doesn't seem very helpful in figuring out exactly what's going wrong. If anyone knows a way to debug that might give a bit more detail, I'd be happy to test my non-working setup :)

**Comment by prurigro** [comment]
Things are still good- I'm gonna close this out.

**Comment by PhilippWoelfel** [comment]
I'm experiencing exactly the same problem...

**Comment by prurigro** [comment]
Wish I could tell you what fixed it- I'm guessing at least the trigger is something on facebook's end. Did it end up resolving itself for you too?

**Comment by viveksjain** [comment]
I'm hitting the same, have been getting these errors for several days. Restart didn't help, just tried logout/login and still getting an error.

**Comment by meyerrj** [comment]
I've been getting this error for the past several weeks as well.

**Comment by naezeroth** [comment]
I've been experiencing this issue for a few months now, and even uninstalling and reinstalling did not fix it.

**Comment by sjnhnp** [comment]
@naezeroth @meyerrj Did you finally solve this problem? and What version of matrix homeserver are you using?
