### ISSUE TITLE
DMs: `@facebookbot` has no profile image in seen

### ISSUE THREAD

**Issue by jtagcat** [mautrix/facebook#263]
Maybe see https://github.com/mautrix/facebook/issues/262 for context

In groups (OU image removed):
![image](https://user-images.githubusercontent.com/38327267/194071697-4530ee89-e794-44cb-8b68-f8b795f583a8.png)

In DMs (first two images removed): 
![image](https://user-images.githubusercontent.com/38327267/194073076-709cd3be-1f08-4551-aeab-9555d199b114.png)

**Comment by tulir** [comment]
This isn't a problem, but the avatar will be there if you enable encryption so the bot joins rooms
