### ISSUE TITLE
Add graphql query type for removing/deleting fb messenger messages

### ISSUE THREAD

**Issue by tonywong332** [mautrix/facebook#269]
FB messages of all conversation participants can be deleted for the user but I don't seem to see this graphql query supported for the mautrix fb api. It would be nice to expose such a query as I'd like to utilize mautrix's fb api for some scripting across messenger conversations.

**Comment by tulir** [comment]
https://github.com/mautrix/facebook/blob/master/maufbapi/http/api.py#L199
