### ISSUE TITLE
Disable `Refreshing session... Connected to Facebook Messenger` message

### ISSUE THREAD

**Issue by HammyHavoc** [mautrix/facebook#275]
Is there a way to disable this? It occupies a spot at the top of my Element messenger most of the time on Android, even with it set to low priority and notifications disabled for the chat.

**Comment by sumnerevans** [comment]
Is this what you are looking for? https://github.com/mautrix/facebook/blob/master/mautrix_facebook/example-config.yaml#L254-L259

**Comment by HammyHavoc** [comment]
Certainly seemed to work! Thank you! :- )
