### ISSUE TITLE
Exception handling/Send error messages to users/potential users

### ISSUE THREAD

**Issue by gabrc52** [mautrix/facebook#309]
Some things you may attempt to do when logging in with the bot fail.

For instance, attempting to log into the bridge with the same Facebook account on two Matrix users fails, throwing an exception. Exceptions could also be thrown on bugs.

It would be nice to show the exceptions back to the users of the bridge, so they don't get stuck in a loading screen or the bridge being responsive.

**Comment by tulir** [comment]
It already does
