### ISSUE TITLE
Filtering community did not work

### ISSUE THREAD

**Issue by christianlupus** [mautrix/facebook#51]
I have a setup according to https://github.com/spantaleev/matrix-docker-ansible-deploy. I set to put all facebook chats in a community on its own. So my config looks like
```
...
bridge:
    username_template: facebook_{userid}
    community_template: unofficial/facebook_{localpart}={server}
...
```

I then enabled the bridge and successfully connected (after a few attempts) with my Facebook account. All right, a new community was generated and some rooms in this community as well. Older chats were not imported. Seems ok. Yay!

I then wanted to open a chat with a contact I did not chat in a long time. The chat was not generated in the first moment during sync. I thus called `sync --contacts` and `sync --create` in the control room.

This started a long-running sync process where all chats were readded but **without** the community. Thus all my chats are now in the main list but not in the community. I seem not to have sufficient rights to change the community to add the rooms to the community manually (although tedious).

I think there is a bug or the documentation needs to be improved that the `sync` command is only for internal usage and might break the installation (plus a potential workaround).

**Comment by yuuki-san** [comment]
better documentation would be nice :)
here are some solutions that come to mind:
1. Solution - try adding this to your vars.yml (if you haven't) ([mentioned in docs of m-d-a-d](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-facebook.md#set-up-community-grouping))
`...
matrix_synapse_configuration_extension_yaml: |
  enable_group_creation: true
  group_creation_prefix: "unofficial/"
...`
2. Solution - restart the bridge by executing `systemctl restart matrix-mautrix-facebook` on your server (my favorite option :D )
3. Solution - re-login with your FB account
4. look at `systemctl status matrix-mautrix-facebook` and `journalctl -u matrix-mautrix-facebook` on your server and if a significant error/warning appears (ansible should have informed you if there was a significant error), it would be probably good to post an issue

**Comment by christianlupus** [comment]
@yuuki-san I have the settings in my `homeserver.yaml` config as you seem to intend. However, I do not get your point, sorry. What does this have to do with the topic of the issue here? I might be misled but do not get the connection.

**Comment by yuuki-san** [comment]
my apologies, I have updated the comment; hope it sounds right now this time :) One thing to also mention is that this behavior (adding/syncing users and their sudden community-less-ness) started after I restarted the bridge
